# Generated by Django 4.2.5 on 2023-09-25 20:06

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Curso",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("curso", models.CharField(max_length=20)),
                ("camada", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Estudiate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=20)),
                ("apellido", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=254)),
            ],
        ),
    ]
