# Generated by Django 4.2.5 on 2023-09-26 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_entregable_profesor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entregable',
            name='fecha_de_entrega',
            field=models.CharField(max_length=20),
        ),
    ]
